name: test-linux

on:
  push:
    branches: [ dev, main ]

  # Run tests once a week on Sunday.
  schedule:
    - cron: "0 6 * * 0"

permissions:
  contents: read

env:
  CMAKE_BUILD_TYPE: Release
  CMAKE_GENERATOR: Ninja
  CTEST_OUTPUT_ON_FAILURE: True

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Create Build Environment
        run: |
          sudo apt update
          sudo apt install -y ninja-build
          cmake -E make_directory ${{github.workspace}}/build

      - name: Install Building Dependencies
        uses: ./.github/actions/building-deps
        with:
          boost: 1.85.0
          oneTBB: 2021.12.0
          python: 3.12
          path: ${HOME}/.local

      - name: Configure
        working-directory: ${{github.workspace}}/build
        run: cmake ..

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config Release

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -VV -C Release